module.exports = {
  someSidebar: {
    Tópicos: [
      "roteiro",
      "publico-alvo",
      "contexto",
      "gestor",
      "certificado",
      "gov.br",
      "portal", 
      "identificador",
      "ti",     
      "servicos",
      "postman",
      "ambientes",
      "tecnologias",
      "requisicoes",
      "perfis",
      "si",
      "resultado",
      "erros",
      "autenticacao",
    ],
    Ferramentas: [
      "tools/api",
      "tools/fhirpath",
      "tools/keytool",
      "tools/validacao",
    ],
  },
};
