@startuml analise

hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

Arquivo -up-|> Entrada
Diretório -up-|> Entrada

"Sentença em FHIRPATH" -right-> Entrada : "Executada sobre"
"Sentença em FHIRPATH" -down-> Lista : " Resultado"
@enduml