@startuml

hide circle
hide methods
hide empty members

skinparam component {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

skinparam interface {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

package "Aplicação Gráfica (opções)" {
    Component "FHIRPath Service" as WS << Spring Boot >>
    Component "GUI" as EGUI <<electron>>
    Component "GUI" as WGUI <<web>>

    EGUI .right.> () "HTTP API" : use
    [HTTP API] - WS
    WGUI .down.> () "HTTP API" : use
}

   WS .right.> () API : use


package "Aplicação CLI" {
    Component CLI
    Component jline3 as JLINE3 <<library>>
    Component "FHIRPath Library" as FPL <<library>>
    Component "Hapifhir" as HF <<FHIR>>
    CLI .down.> API : use
    API - FPL
    FPL .left.> HF : use
    CLI .left.> JLINE3
}

@enduml